BACKLOG-22380: Update source code to use HTML filtering
Jahia/html-filtering pull request #22
Opened 2024-02-15 10:55 UTC by rknj

## JIRA

https://jira.jahia.org/browse/BACKLOG-22380

## Description

Renamed files, classes and variables

2024-02-15 16:15 UTC, cedmail requested changes

2024-02-15 16:15 UTC, cedmail commented on src/main/java/org/jahia/modules/htmlfiltering/graphql/models/GqlRichTextConfig.java
>  public class GqlRichTextConfig implements RichTextConfigInterface {
```suggestion
public class GqlHTMLFilteringConfig implements RichTextConfigInterface {
```
But this needs to be done everywhere

2024-02-15 16:17 UTC, rknj commented on src/main/java/org/jahia/modules/htmlfiltering/graphql/models/GqlRichTextConfig.java
>  public class GqlRichTextConfig implements RichTextConfigInterface {
I guess I missed that one and the related interface

2024-02-15 18:24 UTC, gflores-jahia commented
Renamed most of richtext references to html-filtering. Only thing left would be to change actual repo name/root folder in the github settings once merged probably.

2024-02-16 13:00 UTC, cedmail approved these changes

2024-02-16 14:11 UTC, merged